version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicarefree
      MYSQL_USER: cuidador
      MYSQL_PASSWORD: CuidadorFree
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./medicare-backend
    container_name: medicare-backend
    env_file:
      - ./medicare-backend/.env
    volumes:
      - ./medicare-backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "/wait-for-db.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


  frontend:
    build:
      context: ./medicare-frontend
    container_name: medicare-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./medicare-frontend:/app
    depends_on:
      - backend
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  db_data:
